### ISSUE TITLE
Issue in last release - Uncaught SyntaxError: Unexpected token {

### ISSUE THREAD

**Issue by SeLLeRoNe** [thomasloven/lovelace-card-modder#25] opened 2019-02-15 23:52 UTC
Hi Thomas,

first of all, thanks for the great work and effort you put into this :)

I have just updated this custom card but it is no longer working, this is the error:
card-modder.js?v=c7fa10:74:55 Uncaught SyntaxError: Unexpected token {

I guess there is a typo of sort (or a unclsoed "business" :D) somewhere 

Hope it helps :)

Cheers
Andrea

**Comment by CMaxim77** [comment] 2019-02-16 04:25
I believe the issue is line #74 in the .js

#74 if(root.querySelector("vertical-stack-in-card") {
#75        target = root.querySelector("vertical-stack-in-card");
#76        continue;

Maybe after the ("vertical-stack-in-card") something here is broke?

**Comment by iantrich** [comment] 2019-02-16 04:26
Fixed in https://github.com/thomasloven/lovelace-card-modder/pull/26

**Closed** 2019-02-16 06:23 UTC
